### PR TITLE
Vagrant environment for developing this formula

### PR DESCRIPTION
**Pull request by ashb**
This can be used by `vagrant up` and then `vagrant provision` will use the files in this dir . Make sure the following formulas are up to date and available alongside this dir

- bootstrap
- firewall
- apparmor
- python
- nginx
- repos
- logstash

(Yes that list is huge.)

Also, adds a Jenkins plugin module/state that enables installation of Jenkins plugins via Salt

### CODE REVIEW

**Comment by mikepea** [comment]
This PR is in serious need of a rebase to squish it down into understandable chunks.

Happy to help with that, if @ashb or @milosgajdos83 or @mattmb has a moment.

**Comment by milosgajdos83** [comment]
I would not worry about this one. Let's face it @mikepea - we do not use this anywhere afaik. So let's get this first into sane state so that it's actually usable, tag it with 0.1 and then do proper PR reviews.

**Comment by ashb** [comment]
@milosgajdos83 This repo is in use by two of our projects and at least one by the OPG, and perhaps more importantly a key part of our deploy process - it needs to be maintainable and part of that is having a readable commit history.

**Comment by milosgajdos83** [comment]
Right, I had the impression that it was not and that it was a mess that needs to be fixed. My bad. Ignore my comments then!

**Comment by mikepea** [comment]
Merging as discussed, rebased to make a lot more sense.

**Pull request merged**
