### PR TITLE
Added slave and sudoers state files, which are entirely optional. Split up shared components like ssh setup and gitconfig.

### PR DESCRIPTION
**Pull request by atrull**

### CODE REVIEW

**Comment by milosgajdos83** [comment]
This looks much better. My last comment is - there is a bit of duplication with the SSH stuff in both ```server.sls``` state and ```slave.sls``` state.

Would it be worth to move them into a separate state and then just include them on top of the states they are needed in ? CC: @ashb

**Comment by atrull** [comment]
I've split up the shared states, and this time it appears to be working correctly.

**Comment by milosgajdos83** [comment]
LGTM :+1:

**Comment by mikepea** [comment]
Hey @atrull -- this PR needs to be squashed down to make more sense. The commits where you fix bugs and insert and back-out ideas can be removed.

Please make the ultimate commit messages explain exactly *why* this change is being made -- tbh what you have in the changelog, but expanded a little.

**Comment by ashb** [comment]
@atrull We wanted to get Milos' branch merged too so I hope you don't mind but I squashed the commits for you.

**Pull request merged**
